#Numpy Library
Numpy arrays are similar to lists yet different. It is a central data structure and numpy is short for for “Numerical Python”. It is useful for efficient computation of arrays and matrices.

In [0]:
import numpy as np

**Defining your first 1D array**


In [3]:
first_array=np.array([1,2,3])
print(first_array)

[1 2 3]


**2D array**

In [4]:
second_array=np.array([[1,2,3],[4,5,6]])
print(second_array)

[[1 2 3]
 [4 5 6]]


In [5]:
second_array=np.array([[1,2,3],[4,5,6]], dtype=float)
print(second_array)

[[1. 2. 3.]
 [4. 5. 6.]]


**Indexing**

In [6]:
print"First element in a 1D array =", first_array[0]

First element in a 1D array = 1


In [7]:
print"First element in a 2D array =", second_array[0][0]

First element in a 2D array = 1.0


**Last element of a 2D array**

In [8]:
print"Last element in a 2d array=", second_array[1][-1]

Last element in a 2d array= 6.0


In [9]:
second_array[1][-1]=87
print"Modified second array\n", second_array

Modified second array
[[ 1.  2.  3.]
 [ 4.  5. 87.]]


**Create a new array with 1 row and 2 columns of the 2nd array**

In [10]:
new_array=second_array[:1, :2].copy()
print new_array

[[1. 2.]]


In [11]:
new_array.size

2

**Modify the new array**

In [12]:
new_array[0][1]=20
print new_array

[[ 1. 20.]]


**But why did we use the copy command before?**

In [13]:
print "Original array maintained\n",  second_array

Original array maintained
[[ 1.  2.  3.]
 [ 4.  5. 87.]]


**Numpy array properties**

Dimensions

Size

Memory (bytes)

In [14]:
print "Number of dimensions", second_array.ndim

Number of dimensions 2


In [94]:
print"Second array shape", second_array.shape

Second array shape (2, 3)


In [15]:
print "nbytes", second_array.nbytes,"bytes"

nbytes 48 bytes


**Arrays created for matrix operations**

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**Should always track the type based on usage**

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

**Numpy array compatiblity**

In [48]:
#Define x
x = np.ones((2,3))

# Dimensions of x
print(x.shape)

# Define y`
y = np.ones((2,3))

# Dimensions of y
print(y.shape)
arr_sum= x+ y
# Array addition
print'The array sum is \n',arr_sum

(2, 3)
(2, 3)
The array sum is 
[[2. 2. 2.]
 [2. 2. 2.]]


**Scalar usage**

In [49]:
prod_sum=16*arr_sum
print prod_sum

[[32. 32. 32.]
 [32. 32. 32.]]


In [20]:
z=np.reshape(x,(3,2))
x+z

ValueError: ignored

In [21]:
 x1 = np.array([1, 2, 3, 4, 5])
 x2 = np.array([5, 4, 3])

x1.shape

(5,)

In [22]:
 x1+x2

ValueError: ignored

In [23]:
x1_new=x1[:, np.newaxis] 
x1_new.shape

(5, 1)

In [24]:
x1_new+x2

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

**Concatenating two arrays**

In [40]:
a1=np.array([[1,2], [3,4]])
a1_concat=np.concatenate([a1, a1])
print"Joining a1 and a1 in to a single array\n",a1_concat

Joining a1 and a1 in to a single array
[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [46]:
a1_axis_concat= np.concatenate([a1, a1], axis=1)
print"Joining a1 and a1 in to a single array\n",a1_axis_concat

Joining a1 and a1 in to a single array
[[1 2 1 2]
 [3 4 3 4]]


**hstack for horizontal stack or vstack for vertical stack**

In [45]:
a2= ([[7], [7]])
np.hstack([a1, a2])

array([[1, 2, 7],
       [3, 4, 7]])

**Random number generation**`

In [23]:
np.random.rand(2,3)

array([[0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492]])

**Seed fixes the random output for re-producability and analysis**

In [22]:
np.random.seed(0)
np.random.rand(2,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

In [69]:
np.random.seed(0)
a=np.random.rand(20)
print a

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985
 0.77815675 0.87001215]


**Array reshaping**

In [70]:
a.shape

(20,)

**Dimensionality Increase**

In [124]:
new_axis1=a[:,np.newaxis]
new_axis1.shape

(20, 1)

In [126]:
new_axis2=a[np.newaxis,:]
new_axis2.shape

(1, 20)

In [131]:
b=a.reshape(20,1)
b.shape

(20, 1)

In [130]:
c=b.reshape(1,20)
c.shape

(1, 20)

In [88]:
c=a.reshape(2,2,-1)
c.shape
print c

[[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
  [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]]

 [[0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
  [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]]]


In [86]:
d = np.reshape(c, (c.shape[0], -1))
d.shape

(2, 10)

In [33]:
np.arange(6.28)

array([0., 1., 2., 3., 4., 5., 6.])

In [29]:
#if start value is defined then step has to be defined
np.arange(0,6.28,.1) 

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

Linspace creates evenly spaced value sequence in a defined interval

In [31]:
np.linspace(0, 6.28, 10, retstep=True)

(array([0.        , 0.69777778, 1.39555556, 2.09333333, 2.79111111,
        3.48888889, 4.18666667, 4.88444444, 5.58222222, 6.28      ]),
 0.6977777777777778)

In [35]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [39]:
np.linspace(1, 10, num = 5, dtype=int, endpoint = False)

array([1, 2, 4, 6, 8])